name: auth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.2        # Updated to 5.3.2
  firebase_core: ^3.7.0        # Updated to 3.7.0
  provider: ^6.1.2
  cloud_firestore: ^5.4.5     # Updated to 5.4.5
  pdf: ^3.4.0
  printing: ^5.13.4           
  firebase_storage: ^12.3.5   # Updated to 12.3.5
  image_picker: ^1.1.2
  intl: ^0.19.0               # Updated to 0.19.0
  country_list_pick: ^1.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # No update required for lints

dependency_overrides:
  async: ^2.12.0              
  boolean_selector: ^2.1.2    
  characters: ^1.3.1          
  clock: ^1.1.2               
  collection: ^1.19.1         
  crypto: ^3.0.6              
  fake_async: ^1.3.2          
  file_selector_linux: ^0.9.3  
  file_selector_macos: ^0.9.4+2 
  file_selector_windows: ^0.9.3+3 
  flutter_plugin_android_lifecycle: ^2.0.23 
  http_parser: ^4.1.1         
  image: ^4.3.0               
  image_picker_android: ^0.8.12+17 
  image_picker_for_web: ^3.0.6   
  image_picker_ios: ^0.8.12+1    
  leak_tracker: ^10.0.8        
  leak_tracker_flutter_testing: ^3.0.9 
  matcher: ^0.12.17           
  material_color_utilities: ^0.12.0 
  meta: ^1.16.0               
  mime: ^2.0.0                
  path: ^1.9.1                
  path_parsing: ^1.1.0        
  stack_trace: ^1.12.0        
  string_scanner: ^1.4.0      
  test_api: ^0.7.3            
  typed_data: ^1.4.0          
  vm_service: ^14.3.1         

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
